// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVJC-ruQF1dTk6qFshougv5Dd619uE4-Y',
    appId: '1:540348568025:android:5da1caf9b58dc79a3209c8',
    messagingSenderId: '540348568025',
    projectId: 'sdd-project-2999d',
    storageBucket: 'sdd-project-2999d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClasPivx8eQ4xj3VwRI5CxWuoRR5p-Scw',
    appId: '1:540348568025:web:6da10e8d6d50863e3209c8',
    messagingSenderId: '540348568025',
    projectId: 'sdd-project-2999d',
    authDomain: 'sdd-project-2999d.firebaseapp.com',
    storageBucket: 'sdd-project-2999d.firebasestorage.app',
    measurementId: 'G-V9KFTKMVWY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCupJVsRG-_u1-TS1Pm3uQkQAYc5AleApY',
    appId: '1:540348568025:ios:1e5aa80a8e2aacc63209c8',
    messagingSenderId: '540348568025',
    projectId: 'sdd-project-2999d',
    storageBucket: 'sdd-project-2999d.firebasestorage.app',
    iosBundleId: 'com.example.smp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCupJVsRG-_u1-TS1Pm3uQkQAYc5AleApY',
    appId: '1:540348568025:ios:1e5aa80a8e2aacc63209c8',
    messagingSenderId: '540348568025',
    projectId: 'sdd-project-2999d',
    storageBucket: 'sdd-project-2999d.firebasestorage.app',
    iosBundleId: 'com.example.smp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClasPivx8eQ4xj3VwRI5CxWuoRR5p-Scw',
    appId: '1:540348568025:web:dd24ae10003367bd3209c8',
    messagingSenderId: '540348568025',
    projectId: 'sdd-project-2999d',
    authDomain: 'sdd-project-2999d.firebaseapp.com',
    storageBucket: 'sdd-project-2999d.firebasestorage.app',
    measurementId: 'G-5J212SZ1FL',
  );

}